node {
    stage('Build') {
        docker.image('python:2-alpine').inside {
            echo 'Building the application...'
            sh 'ls -lah sources/' 
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            echo 'Running tests...'
            sh 'ls -lah sources/'  
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        }
        junit 'test-reports/results.xml' 
    }

    stage('Deliver') {
    node {
        docker.image('cdrx/pyinstaller-linux:python2').inside('-v ${WORKSPACE}/sources:/app') {
            echo 'Packaging the application...'
            
            // Cek apakah file ada di /app sebelum eksekusi PyInstaller
            sh 'ls -lah /app'  
            
            // Tambahkan sleep untuk debugging jika file belum siap
            sh 'sleep 3'
            
            // Jalankan PyInstaller
            sh 'pyinstaller --onefile /app/add2vals.py'
        }

        // Archive hasil build jika berhasil
        archiveArtifacts artifacts: 'dist/add2vals', fingerprint: true
    }
}

}
