node {
    stage('Checkout Code') {
        git branch: 'master', url: 'https://github.com/Ziddma/simple-python-pyinstaller-app.git'
    }

    stage('Build') {
        docker.image('python:3.9').inside {
            sh 'python3 -m py_compile ./sources/add2vals.py ./sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            try {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            } finally {
                junit 'test-reports/results.xml'
            }
        }
    }

    stage('Manual Approval') {
        script {
            input message: 'Melanjutkan tahap deploy? (Klik "Proceed" untuk menlanjutkan)' 
        }
    }

    stage('Deploy') {
        docker.image('python:3.9').inside('--network=host -u root') {
            sh 'pip install --no-cache-dir pyinstaller'
            sh 'pyinstaller --onefile sources/add2vals.py'
        }
        archiveArtifacts 'dist/add2vals'
        
        
        sh 'sleep 60'
    }

}
