node {
    stage('Build') {
        docker.image('python:2-alpine').pull()
        docker.image('python:2-alpine').inside {
            echo 'Building the application...'
            sh 'ls -lah sources/'  // Cek apakah file ada
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').pull()
        docker.image('qnib/pytest').inside {
            echo 'Running tests...'
            sh 'ls -lah sources/'  // Cek apakah file masih ada sebelum test
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        }
    }

    stage('Publish Test Results') {
        junit 'test-reports/results.xml'
    }

    stage('Deliver & Archive') {
        echo 'Checking if sources/add2vals.py exists...'
        sh 'ls -lah sources/'

        echo 'Pulling Docker Image for PyInstaller...'
        sh 'docker pull cdrx/pyinstaller-linux:python2'

        echo 'Running PyInstaller...'
        sh 'docker run --rm -v $(pwd):/src -w /src cdrx/pyinstaller-linux:python2 pyinstaller --onefile sources/add2vals.py'

        archiveArtifacts artifacts: 'dist/add2vals', fingerprint: true
    }
}
